name: Setup Bowtie
description: "Install Bowtie, hooray!"
author: "Julian Berman"
branding:
  icon: package
  color: blue

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      id: localpython
      with:
        python-version: "3.10 - 3.11"
        update-environment: false

    - name: "Install Bowtie"
      run: pipx install --python "${{ steps.localpython.outputs.python-path }}" bowtie-json-schema
      shell: bash
